# Use an official OpenJDK runtime as a parent image
FROM openjdk:17-jdk-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the Maven/Gradle build artifact to the container
COPY target/travelExperts-0.0.1-SNAPSHOT.jar app.jar

# Expose the port your application runs on
EXPOSE 8080

# Run the application
ENTRYPOINT ["java", "-Xms256m", "-Xmx256m", "-XX:MaxMetaspaceSize=128m", "-jar", "app.jar"]